import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GradualBlurMemo from "@/blocks/Animations/GradualBlur/GradualBlur";
import Particles from "@/blocks/Backgrounds/Particles/Particles";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen relative`}
      >
        <div className="absolute inset-0 w-full h-full z-0 pointer-events-none">
          <Particles particleCount={20000} />
        </div>
        <GradualBlurMemo
          opacity={1}
          strength={1}
          preset="page-footer"
          divCount={10}
          height="2rem"
        />
        {children}
      </body>
    </html>
  );
}
