import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GradualBlurMemo from "@/blocks/Animations/GradualBlur/GradualBlur";
import Particles from "@/blocks/Backgrounds/Particles/Particles";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <div className="fixed w-screen h-screen z-10 pointer-events-none">
          <Particles particleCount={2000} />
        </div>

        <div className="relative">
          <GradualBlurMemo
            opacity={1}
            strength={1}
            preset="page-footer"
            divCount={10}
            height="2rem"
          />
          {children}
        </div>

        <ToastContainer />
      </body>
    </html>
  );
}
